### PR TITLE
Add support for `image/*` MIME type

### LINKED ISSUE #4: `size` filter does not support webp image format
Say I use the filter like `{{ "/assets/img/test.png" | size: 480 }}` then it outputs `/assets/img/test-480w.png`. But if the file is `test.webp` it outputs `/assets/img/` without the file name. 

I think it's because of the following line, but the `srcset` function has it too, yet it works.

https://github.com/lawmurray/jekyll-responsive-magick/blob/4f809ea4a0629f7ea728bb26629498446397479b/lib/jekyll-responsive-magick.rb#L145

### PR DESCRIPTION
**Pull request by d9beuD**
- Closes #4
- Refactor check functions
- Use MIME type to check if the file is a valid image

### CODE REVIEW

**Comment by lawmurray** [comment]
Looking good @d9beuD, thanks for putting this together.

Any chance there's a way to check MIME type without pulling in `ruby-filemagic` or any other gem dependency? One of the motivations I had for this plugin was to avoid having to install extra Ruby Gems, as that's a showstopper for some deployments (Cloudflare Pages, for example). That's why the command-line interface to ImageMagick is used instead of the `rmagick` gem, for example, and it means you can just put `jekyll-responsive-magick.rb` in your Jekyll `_plugins` folder to get it working, without having to gem install.

If there's not a way to check MIME type without additional dependencies,we might want to go back to file extension checks instead.

**Comment by d9beuD** [comment]
Thanks for your feedback @lawmurray. I understand your point of view, actually I first searched a way to do this by command line but couldn't find CLI tool that works the same for Linux, macOS and Windows.

Anyway, I think I can use ImageMagick's `identify` command to check if it's an image file that is provided as it throws an error when it's not.

```sh
$ identify test.txt
identify: improper image header `test.txt' @ error/txt.c/ReadTXTImage/417.
```

**Comment by d9beuD** [comment]
`srcset` filter does not really need `is_image?` check because it already uses ImageMagick's `identify` command in order to get image dimensions.

**Comment by lawmurray** [comment]
Looks good @d9beuD, thanks again for putting this together, nice piece of work! I think this unblocks you on #3 too. I may wait for that, or at least do a little more testing, before updating on RubyGems.

**Pull request merged**
